#uselib "ia32.dll"
#func CPU_CALL_FAR "CPU_CALL_FAR" int,int
#func CPU_EXECUTE "CPU_EXECUTE"
#func CPU_FINISH "CPU_FINISH"
#func CPU_INIT "CPU_INIT"
#func CPU_IRET "CPU_IRET"
#func CPU_JMP_FAR "CPU_JMP_FAR" int,int
#func CPU_LOAD_LDTR "CPU_LOAD_LDTR" int
#func CPU_LOAD_TR "CPU_LOAD_TR" int
#cfunc CPU_POP "CPU_POP"
#func CPU_PUSH "CPU_PUSH" int
#func CPU_PUSHF "CPU_PUSHF"
#cfunc CPU_READ_STACK "CPU_READ_STACK"
#func CPU_RELEASE "CPU_RELEASE"
#func CPU_RESET "CPU_RESET"
#func CPU_SET_MACTLFC "CPU_SET_MACTLFC" int
#func CPU_SOFT_INTERRUPT "CPU_SOFT_INTERRUPT" int
#cfunc CPU_TRANS_PAGING_ADDR "CPU_TRANS_PAGING_ADDR" int
#func CPU_WRITE_STACK "CPU_WRITE_STACK" int
#cfunc CPU_GET_REG "CPU_GET_REG" int
#func CPU_SET_REG "CPU_SET_REG" int,int
#func CPU_SET_IRQ "CPU_SET_IRQ" int
#func CPU_SET_A20 "CPU_SET_A20" int
#func CPU_REQ_INTERRUPT "CPU_REQ_INTERRUPT" int
#func CPU_REQ_NMINTERRUPT "CPU_REQ_NMINTERRUPT"
#func CPU_EXECUTE_CC "CPU_EXECUTE_CC" int
#cfunc CPU_GET_SYSREG "CPU_GET_SYSREG" int
#func CPU_SET_SYSREG "CPU_SET_SYSREG" int,int
#cfunc CPU_GET_SYSREG_DESC "CPU_GET_SYSREG_DESC" int
#func CPU_SET_SYSREG_DESC "CPU_SET_SYSREG_DESC" int,int
#cfunc CPU_GET_SYSREG_LIMIT "CPU_GET_SYSREG_LIMIT" int
#func CPU_SET_SYSREG_LIMIT "CPU_SET_SYSREG_LIMIT" int,int
#cfunc CPU_GET_CR0 "CPU__GET_CR0"
#func CPU_SET_CR0 "CPU__SET_CR0" int
#cfunc CPU_GET_CR1 "CPU__GET_CR1"
#func CPU_SET_CR1 "CPU__SET_CR1" int
#cfunc CPU_GET_CR2 "CPU__GET_CR2"
#func CPU_SET_CR2 "CPU__SET_CR2" int
#cfunc CPU_GET_CR3 "CPU__GET_CR3"
#func CPU_SET_CR3 "CPU__SET_CR3" int
#cfunc CPU_GET_CR4 "CPU__GET_CR4"
#func CPU_SET_CR4 "CPU__SET_CR4" int
#cfunc CPU_GET_LDTR "CPU_GET_LDTR"
#func CPU_SET_LDTR "CPU_SET_LDTR" int
#cfunc CPU_GET_TR "CPU_GET_TR"
#func CPU_SET_TR "CPU_SET_TR" int
#cfunc CPU_GET_MXCSR "CPU__GET_MXCSR"
#func CPU_SET_MXCSR "CPU__SET_MXCSR" int
#func CPU_SET_SS32 "CPU_SET_SS32" int
#func CPU_SET_PM "CPU_SET_PM" int
#func CPU_SET_OP32 "CPU_SET_OP32" int
#func CPU_SET_AS32 "CPU_SET_AS32" int
#func CPU_SWITCH_PM "CPU_SWITCH_PM" int
#func CPU_SET_IDTR_BASE "CPU_SET_IDTR_BASE" int
#func CPU_SET_IDTR_LIMIT "CPU_SET_IDTR_LIMIT" int
#func CPU_SET_GDTR_BASE "CPU_SET_GDTR_BASE" int
#func CPU_SET_GDTR_LIMIT "CPU_SET_GDTR_LIMIT" int
